#!/usr/bin/env python
from pathlib import Path
import snakemake
import argparse
import shutil
import os


def init_workflow(args):
    files = ("assemblies.tsv", "config.yaml", "samples.tsv")
    origin = Path(__file__).resolve().parent / "assets"
    target = Path(os.getcwd())
    for file in files:
        o = origin / file
        t = target / file
        shutil.copy(o, t)


def run_workflow(args):
    args = vars(args)
    del args["func"]
    snakemake.snakemake(
        "Snakefile", 
        **args
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(help="Choose init or run.")

    # Init parser
    init_parser = subparsers.add_parser("init", help="Initialize the pipeline in the current directory.")
    init_parser.set_defaults(func=init_workflow)

    # Run parser
    run_parser = subparsers.add_parser("run", help="Runs the pipeline in the current working directory.")
    run_parser.set_defaults(func=run_workflow)

    # Add the --dry-run (or -n) argument
    run_parser.add_argument(
        "--dry-run",
        "-n",
        dest="dryrun",
        action="store_true",
        help="If specified, runs the script in dry-run mode (do not actually execute actions).",
    )

    # Add the --cores (or -c) argument
    run_parser.add_argument(
        "--cores",
        "-c",
        dest="cores",
        type=int,
        default=1,
        help="Number of cores to use (default is 1).",
    )

    args = parser.parse_args()
    if hasattr(args, "func"):
        args.func(args)
    else:
        parser.print_help()
